FlaskApp/forms/restaurants.py
from flask_wtf import FlaskForm
from wtforms.fields import *
from wtforms.validators import Email, InputRequired, Length, URL


class RestaurantForm(FlaskForm):
    """Create WTForm to add restaurants"""
    name = StringField('Name', validators=[InputRequired()])
    phone = StringField('Phone #', validators=[InputRequired()])
    email = StringField('E-Mail', validators=[InputRequired(),
                                              Email("This field requires a valid email address")])
    course = SelectField(u'Course', choices=[('American', 'American'), ('Mexican', 'Mexican'),
                                             ('India', 'India'), ('Mediterranean', 'Mediterranean'),
                                             ('Caribbean', 'Caribbean'), ('Asia', 'Asia'),
                                             ('Mix', 'Mix')], validators=[InputRequired()])
    description = TextAreaField('Description', validators=[InputRequired(), Length(min=5, max=200)])
    website = StringField('Website', validators=[InputRequired(),
                                                 URL(require_tld=True, message="Enter a valid URL")])
    street = StringField('Street', validators=[InputRequired()])
    city = StringField('City', validators=[InputRequired()])
    state = StringField('State', validators=[InputRequired()])
    zip_code = StringField('Zip Code', validators=[InputRequired()])

FlaskApp/views/menu_items.py
# flask imports
from flask import render_template, request, redirect, url_for, flash, Blueprint
from flask import session as login_session
from FlaskApp.views.auth import login_required
from FlaskApp.database import db_session, MenuItem, Restaurant

from FlaskApp.forms.menu_items import MenuItems

menu_b = Blueprint('menu_b', __name__)


@menu_b.route('/restaurants/<int:restaurant_id>/menu/new', methods=['GET', 'POST'])
@login_required
def create_menu_restaurant(restaurant_id):
    """Created route and function to create new menu items
        for each restaurant"""
    if Restaurant.user_creator(login_session['user_id'], restaurant_id):
        form = MenuItems()
        if form.validate_on_submit():
            new_item = MenuItem(name=form.name.data,
                                price=form.price.data,
                                course=form.course.data,
                                description=form.description.data,
                                restaurant_id=restaurant_id,
                                user_id=login_session['user_id'])
            db_session.add(new_item)
            db_session.commit()
            return redirect(url_for('restaurant_b.restaurant_detail', restaurant_id=restaurant_id))
        else:
            return render_template('menu_item/newMenuItem.html', form=form, restaurant_id=restaurant_id)
    else:
        flash("You cannot made any changes, make your own restaurant and try again")
        return redirect(url_for('restaurant_b.show_restaurants'))


@menu_b.route('/restaurants/<int:restaurant_id>/menu/<int:menu_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_menu_item(restaurant_id, menu_id):
    """Created route and function to edit each menu item in a restaurant"""
    if Restaurant.user_creator(login_session['user_id'], restaurant_id):
        menu = db_session.query(MenuItem).filter_by(restaurant_id=restaurant_id, id=menu_id).first()
        form = MenuItems()
        if form.validate_on_submit():
            menu.name = form.name.data
            menu.price = form.price.data
            menu.course = form.course.data
            menu.description = form.description.data
            db_session.add(menu)
            db_session.commit()
            return redirect(url_for('restaurant_b.restaurant_detail', restaurant_id=restaurant_id))
        else:
            form.description.data = menu.description
            return render_template("menu_item/editMenuItem.html", form=form, menu=menu,
                                   restaurant_id=restaurant_id, menu_id=menu_id)
    else:
        flash("You cannot made any changes, make your own restaurant and try again")
        return redirect(url_for('restaurant_b.show_restaurants'))


@menu_b.route('/restaurants/<int:restaurant_id>/menu/<int:menu_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_menu_item(restaurant_id, menu_id):
    """Created route and function to delete a menu item"""
    if Restaurant.user_creator(login_session['user_id'], restaurant_id):
        menu = db_session.query(MenuItem).filter_by(restaurant_id=restaurant_id, id=menu_id).first()
        if request.method == 'POST':
            db_session.delete(menu)
            db_session.commit()
            return redirect(url_for('restaurant_b.show_restaurants'))

        return render_template("menu_item/deleteMenuItem.html", menu=menu, restaurant_id=restaurant_id)

    else:
        flash("You cannot made any changes, make your own restaurant and try again")
        return redirect(url_for('restaurant_b.show_restaurants'))

FlaskApp/views/restaurant.py
from flask import render_template, request, redirect, url_for, flash, Blueprint
from flask import session as login_session
from FlaskApp.views.auth import login_required
from FlaskApp.database import db_session, MenuItem, Restaurant, RestaurantAddress

from sqlalchemy import desc

from FlaskApp.forms.restaurants import RestaurantForm

restaurant_b = Blueprint('restaurant_b', __name__)


@restaurant_b.route('/')
def show_restaurants():
    """Created route and function to display the
       restaurant list """
    restaurants = db_session.query(Restaurant).order_by(desc(Restaurant.name))
    if restaurants:
        if 'user_id' in login_session:
            print ('user_id in login_session')
            return render_template('restaurant/restaurants.html', restaurants=restaurants, hello="database found")
        else:
            print ('user_id not in login_session')
            return render_template('restaurant/restaurants.html', restaurants=restaurants)
    else:
        return render_template('restaurant/restaurants.html', restaurants=restaurants, hello="no database")


@restaurant_b.route('/<int:restaurant_id>/menu/')
@restaurant_b.route('/<int:restaurant_id>/')
def restaurant_detail(restaurant_id):
    """Created route and function to display the
        restaurant main page and menu individually"""
    try:
        restaurant = db_session.query(Restaurant).filter_by(id=restaurant_id).one()
        address = db_session.query(RestaurantAddress).filter_by(id=restaurant_id).one()
        items = db_session.query(MenuItem).filter_by(restaurant_id=restaurant.id)
        return render_template("restaurant/restaurantownpage.html", restaurant=restaurant, items=items, address=address)

    except:
        return render_template("restaurant/restaurants.html", error="Restaurant Not Found")


@restaurant_b.route('/new', methods=['GET', 'POST'])
@login_required
def create_restaurant():
    form = RestaurantForm()

    if form.validate_on_submit():
        add_values = Restaurant(name=form.name.data,
                                phone=form.phone.data,
                                food_type=form.course.data,
                                email=form.email.data,
                                website=form.website.data,
                                description=form.description.data,
                                user_id=login_session['user_id'])
        db_session.add(add_values)
        db_session.commit()
        db_session.refresh(add_values)
        add_address = RestaurantAddress(street=form.street.data,
                                        city=form.city.data,
                                        state=form.state.data,
                                        zip_code=form.zip_code.data,
                                        restaurant_id=add_values.id)
        db_session.add(add_address)
        db_session.commit()
        flash("New restaurant Created")
        return redirect(url_for('.show_restaurants'))

    else:
        return render_template("restaurant/newRestaurant.html", form=form)


@restaurant_b.route('/<int:restaurant_id>/delete/', methods=['GET', 'POST'])
@login_required
def delete_restaurant(restaurant_id):
    """Created route and function to delete restaurants individually"""
    if Restaurant.user_creator(login_session['user_id'], restaurant_id):
        restaurant = db_session.query(Restaurant).filter_by(id=restaurant_id).one()
        address = db_session.query(RestaurantAddress).filter_by(restaurant_id=restaurant.id).one()
        if request.method == 'POST':
            db_session.delete(address)
            db_session.delete(restaurant)
            db_session.commit()
            flash("Your Restaurant have been deleted")
            return redirect(url_for('.show_restaurants'))

        return render_template("restaurant/deleteRestaurant.html", restaurant=restaurant)
    else:
        flash("You cannot made any changes, make your own restaurant and try again")
        return redirect(url_for('.show_restaurants'))


@restaurant_b.route('/<int:restaurant_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit_restaurant(restaurant_id):
    """Created route and function to edit restaurants"""
    if Restaurant.user_creator(login_session['user_id'], restaurant_id):
        restaurant = db_session.query(Restaurant).filter_by(id=restaurant_id).one()
        address = db_session.query(RestaurantAddress).filter_by(restaurant_id=restaurant.id).one()
        form = RestaurantForm()
        if form.validate_on_submit():
            restaurant.name = form.name.data
            restaurant.phone = form.phone.data
            restaurant.email = form.email.data
            restaurant.course = form.course.data
            restaurant.description = form.description.data
            restaurant.website = form.website.data
            db_session.add(restaurant)

            db_session.commit()
            db_session.refresh(restaurant)
            address.street = form.street.data
            address.city = form.city.data
            address.state = form.state.data
            address.zip_code = form.zip_code.data
            db_session.add(address)
            db_session.commit()
            flash("Your restaurant have been edited successfully")
            return redirect(url_for('.show_restaurants'))
        else:
            form.description.data = restaurant.description
            return render_template("restaurant/editrestaurant.html", form=form, restaurant=restaurant, address=address)
    else:
        flash("You cannot made any changes, make your own restaurant and try again")
        return redirect(url_for('.show_restaurants'))

FlaskApp/templates/restaurant/deleteRestaurant.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
    <form method="POST" action="{{ url_for('.delete_restaurant', restaurant_id=restaurant.id) }}">
        <h1 class="featurette-heading">Are you sure that you want to delete <span class="text-muted">{{ restaurant.name }}</span>?</h1>
        <button type="submit" class="btn btn-success">Yes Delete</button>
        <a class="btn btn-danger" href="{{ url_for('.show_restaurants') }}">Cancel</a>
    </form>

    </div>
{% endblock %}

FlaskApp/templates/restaurant/editRestaurant.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <div class="container">
	<form class=" well form-horizontal top-margin" method="POST" action="{{url_for('.edit_restaurant', restaurant_id=restaurant.id)}}">
        <legend>Create New Restaurant</legend>
	    {{ form.csrf_token }}
	    {{ wtf.form_field(form.name,form_type="horizontal", horizontal_columns=('lg', 4, 4), value=restaurant.name)}}
	    {{ wtf.form_field(form.phone, form_type="horizontal", horizontal_columns=('lg', 4, 4), value=restaurant.phone)}}
        {{ wtf.form_field(form.email, form_type="horizontal", horizontal_columns=('lg', 4, 4), value=restaurant.email)}}
        {{ wtf.form_field(form.course, form_type="horizontal", horizontal_columns=('lg', 4, 4)) }}
        {{ wtf.form_field(form.description, form_type="horizontal",horizontal_columns=('lg', 4, 4))}}
        {{ wtf.form_field(form.website, form_type="horizontal", horizontal_columns=('lg', 4, 4),value=restaurant.website)}}
        {{ wtf.form_field(form.street, form_type="horizontal", horizontal_columns=('lg', 4, 4),value=address.street)}}
        {{ wtf.form_field(form.city, form_type="horizontal", horizontal_columns=('lg', 4, 4),value=address.city) }}
        {{ wtf.form_field(form.state, form_type="horizontal", horizontal_columns=('lg', 4, 4),value=address.state)}}
        {{ wtf.form_field(form.zip_code, form_type="horizontal", horizontal_columns=('lg', 4, 4),value=address.zip_code)}}

        <input type="submit" class="btn btn-primary" value="update">
        <button type="submit"class="btn btn-danger"><a href="{{ url_for('.show_restaurants') }}">Cancel</a></button>
	</form>
    </div>
    <div class="container">

    </div>
{% endblock %}

FlaskApp/templates/restaurant/index.html
{# This simple template derives from ``base.html``. See ``base.html`` for
   more information about template inheritance. #}
{%- extends "base.html" %}

{# Loads some of the macros included with Flask-Bootstrap. We are using the
   utils module here to automatically render Flask's flashed messages in a
   bootstrap friendly manner #}
{% import "bootstrap/utils.html" as utils %}


{# Inside the ``content`` is where you should place most of your own stuff.
   This will keep scripts at the page end and a navbar you add on later
   intact. #}
{% block content %}
  <div class="container">
  {%- with messages = get_flashed_messages(with_categories=True) %}
  {%- if messages %}
    <div class="row">
      <div class="col-md-12">
        {{utils.flashed_messages(messages)}}
      </div>
    </div>
  {%- endif %}
  {%- endwith %}
    <div class="jumbotron">
      <h1>Welcome to Flask-Bootstrap</h1>
      <p>This example application demonstrates some (but not all!) of the
      features of <a href="http://pythonhosted.org/Flask-Bootstrap">
      Flask-Bootstrap</a>.</p>
      <p>
        <a class="btn btn-lg btn-default" role="button"
           href="http://pythonhosted.org/Flask-Bootstrap" >Show docs</a>
      </p>
    </div>
   </div>
{%- endblock %}

FlaskApp/templates/restaurant/newRestaurant.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <div class="container">
	<form class=" well form-horizontal top-margin" method="POST" action="{{url_for('.create_restaurant')}}">
        <legend><h1>Create New Restaurant</h1></legend>
	    {{ form.csrf_token }}
	    {{ wtf.form_field(form.name,form_type="horizontal", horizontal_columns=('lg', 4, 4), button_map={})}}
	    {{ wtf.form_field(form.phone, form_type="horizontal", horizontal_columns=('lg', 4, 4), button_map={}) }}
        {{ wtf.form_field(form.email, form_type="horizontal", horizontal_columns=('lg', 4, 4), button_map={}) }}
        {{ wtf.form_field(form.course, form_type="horizontal", horizontal_columns=('lg', 4, 4)) }}
        {{ wtf.form_field(form.description, form_type="horizontal", horizontal_columns=('lg', 4, 4), button_map={}) }}
        {{ wtf.form_field(form.website, form_type="horizontal", horizontal_columns=('lg', 4, 4), button_map={}) }}
        {{ wtf.form_field(form.street, form_type="horizontal", horizontal_columns=('lg', 4, 4), button_map={}) }}
        {{ wtf.form_field(form.city, form_type="horizontal", horizontal_columns=('lg', 4, 4), button_map={}) }}
        {{ wtf.form_field(form.state, form_type="horizontal", horizontal_columns=('lg', 4, 4), button_map={}) }}
        {{ wtf.form_field(form.zip_code, form_type="horizontal", horizontal_columns=('lg', 4, 4), button_map={}) }}

        <input type="submit" class="btn btn-primary" value="Create">
        <a class="btn btn-danger" href="{{ url_for('.show_restaurants')}}">Cancel</a>

	</form>
    </div>
    <div class="container">

    </div>
{% endblock %}

FlaskApp/templates/restaurant/restaurantownpage.html
{% extends "base.html" %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="hero-image">
                <img src="/static/img/restaurant-1920x1080-opacity.jpg">
                <div class="wrapper">
                    <h1 class="hero-content hero-title">{{ restaurant.name }}</h1>
                    <h2 class="hero-content hero-subtitle">Official Restaurant Page</h2>
                    <nav class="navbar navbar-inverse" role="navigation">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse"
                                    data-target=".navbar-ex2-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="#">{{ restaurant.name }}</a>
                        </div>

                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse navbar-ex2-collapse">
                            <ul class="nav navbar-nav navbar-right">
                                <li><a href="#">Menu</a></li>
                                <li><a href="#">Contact Us</a></li>
                                {% if 'username' in session %}
                                {% if restaurant.user_id == session['user_id'] %}
                                    <li><a href="{{ url_for('restaurant_b.edit_restaurant', restaurant_id = restaurant.id) }}">Edit Restaurant</a></li>
                                    <li><a href="{{ url_for('restaurant_b.delete_restaurant', restaurant_id = restaurant.id) }}">Delete Restaurant</a></li>
                                    <li><a href="{{ url_for('menu_b.create_menu_restaurant', restaurant_id = restaurant.id) }}">New Menu</a></li>
                                {% endif %}
                                {% endif %}
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li class="active"><a href="#">About</a></li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <section id="about">
        <div class="container">
            <div class="row">
                <div class="col-md-12 title-about">
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <h2 class="text-center">About Us</h2>
                        <hr>
                    </div>
                    <div class="col-md-4"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 subtitle-about">
                    <p class="text-center">{{ restaurant.description }}</p>
                </div>
            </div>
        </div>
    </section>
    <section id="menu">
        <div class="container">
        <div class="row">
            <div class="col-md-12 title-menu">
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <h2 class="text-center">Our Menu</h2>
                    </div>
                    <div class="col-md-4"></div>
                </div>
        </div>
            <div class="row">
            <div class="col-md-12 subtitle-menu">
                {% for item in items %}
                <div class="col-md-6 equal margin-b">
                    <div class="well equal">
                        <h4 class="pull-right">$ {{ item.price }}</h4>
                        <h4>{{ item.name }}</h4>
                        <p>{{ item.description }}</p>
                        <div class="btn-toolbar">
                            <a class="pull-right" href="{{ url_for('menu_b.edit_menu_item', restaurant_id=restaurant.id, menu_id=item.id) }}"><button class="btn btn-primary">Edit</button></a>
                            <a class="pull-right margin-btn" href="{{ url_for('menu_b.delete_menu_item', restaurant_id=restaurant.id, menu_id=item.id) }}"><button class="btn btn-danger">delete</button></a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            </div>
        </div>
    </section>
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="col-md-4"></div>
                    <div class="col-md-4">
                        <h2 class="text-center">Contact Us</h2>
                        <hr>
                    </div>
                    <div class="col-md-4"></div>
                </div>
            </div>
            <div class="row">
                <ul class="nav ">
                    <li><h4>Email: {{ restaurant.email }} </h4></li>
                    <li><h4>Phone: {{ restaurant.phone }}</h4></li>
                    <li><h4>Location: {{ address.street }} {{ address.city }} {{ address.state }} {{ address.zip_code }}</h4></li>
                </ul>
            </div>
        </div>

    </section>



{% endblock %}

FlaskApp/templates/restaurant/restaurants.html
{% extends "base.html" %}
{% block content %}


    <div id="wrapper">
        <div id="sidebar-menu">
            <legend>Filter By restaurant</legend>
            <ul class="sidebar-nav">
                {%  if restaurants %}
                {% for restaurant in restaurants %}
                    <li><a href="#">{{ restaurant.name }}</a></li>
                {% endfor %}
                {% endif %}
            </ul>
        <legend>Filter By Location</legend>
            <ul class="sidebar-nav">
                {%  if restaurants %}
                {% for city in address %}
                    <li><a href="#">{{ city.city }}</a></li>
                {% endfor %}
                {% endif %}
            </ul>
        <legend>Filter By Food</legend>
            <ul class="sidebar-nav">
                {%  if restaurants %}
                {% for food in restaurants %}
                    <li><a href="#">{{ food.food_type }}</a></li>
                {% endfor %}
                {% endif %}
            </ul>
        </div>

     <div id="content-wrapper">
        <div class="container-fluid">
            <div class="row">
                {% if error %}
                    <h3>{{ error }}</h3>
                {% endif %}
            </div>
            <div class = 'flash'>
		      {% with messages = get_flashed_messages() %}
                {% if messages %}

                    <ul>
                    {% for message in messages %}
                        <div class="alert alert-warning">
                            <li> <strong> {{ message }} </strong> </li>
                        </div>
                    {% endfor %}
                    </ul>
                {% endif %}
              {% endwith %}

            </div>
            <div class="row">
                <div class="col-lg-offset-1 col-md-6 col-lg-offset-5">
                    <legend><h1>Restaurants</h1></legend>
                    <a href="#" class="btn btn-primary pull-right" id="menu-toggle">Filters</a>
                </div>
            </div>
            <div class="row restaurant-list">
            <div class="col-lg-offset-1 col-md-6 col-lg-offset-5">
                {%  if restaurants %}
                {% for restaurant in restaurants %}
                    <div class="row well">
                        <div class="col-md-4">
                            <img class="img-responsive" src="http://placehold.it/350x150">
                        </div>
                        <div class="col-md-6">
                            <div class="col-md-6">
                                <h3>{{ restaurant.name }}</h3>
                                <p>{{ restaurant.food_type }} food</p>
                                <br>
                                <p>Read Reviews</p>
                            </div>
                            <div class="col-md-4 pull-right">
                                <a href="{{ url_for('.restaurant_detail', restaurant_id = restaurant.id)}}" class="btn btn-primary" id="menu-toggle">Menu</a>
                                <a href="{{ url_for('.edit_restaurant', restaurant_id = restaurant.id)}}" class="btn btn-success" id="menu-toggle">Edit</a>
                            </div>
                        </div>
                    </div>

                {% endfor %}
                {% endif %}
            </div>
            </div>
        </div>
     </div>
    </div>

{% endblock %}